name: URL Test

on:
   workflow_dispatch:  # Run on manual trigger

jobs:
   build:
     runs-on: ubuntu-20.04

     steps:
       - uses: actions/checkout@v2.4.2

       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install colorama
           pip install beautifulsoup4
       - name: Run URL Tester
         run: python url_test.py
